zuul:
  routes:
    provider: /aaa/**
  ignored-patterns:
    - /**/provider/bus/test
  sensitive-headers:
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9001
spring:
  rabbitmq:
    host: 192.168.1.105
    port: 5672
    username: guest
    password: guest
